artikel/urls.py
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static
from .views import (
    ArticleListView, 
    ArticleDetailView, 
    ArticleKategoriListView,
    # ArticleCreateView,
    ArticleManageView,
    ArticleDetailView,
    ArticleDeleteView,
    # ArticleUpdateView,
    )
app_name = 'blog'
urlpatterns = [
    # path('manage/update/<int:pk>',ArticleUpdateView.as_view(), name='update'),
    path('manage/delete/<int:pk>',ArticleDeleteView.as_view(), name='delete'),
    path('manage',ArticleManageView.as_view(), name='manage'),
    # path('create',ArticleCreateView.as_view(), name='create'),
    path('kategori/<str:kategori>/<int:page>', ArticleKategoriListView.as_view(), name='category'),
    path('detail/<slug:slug>', ArticleDetailView.as_view(), name='detail'),
    path('', ArticleListView.as_view(), name='list'),
    path('<int:page>', ArticleListView.as_view(), name='list'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView
from .views import HomeListView
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('',HomeListView.as_view(), name='home'),
    path('<int:page>',HomeListView.as_view(), name='home'),
    path('artikel/', include('artikel.urls', namespace='artikel')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

artikel/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Artikel(models.Model):
    judul           = models.CharField(max_length=255)
    isi             = models.TextField()
    kategori        = models.CharField(max_length=255)
    author          = models.CharField(max_length=255)
    published       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)
    slug            = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.judul)
        super().save()

    def get_absolute_url(self):
        url_slug = {'slug': self.slug}
        return reverse('artikel:detail', kwargs = url_slug)

    
    def __str__(self):
        return "{}. {}".format(self.author, self.judul)

class File(models.Model):
    Artikel         = models.ForeignKey(Artikel,related_name='File' ,on_delete=models.CASCADE)
    image           = models.ImageField(upload_to='image/')

artikel/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
    )
from .models import Artikel
from django.shortcuts import get_object_or_404
# Create your views here.
# class ArticleUpdateView(UpdateView):
#     model = Artikel
#     form_class = ArtikelForm
#     template_name = 'artikel/article_create.html'
#     extra_context = {
#         'page_title':'Update Article',
#         'button':'Update'
#         }

class ArticleDeleteView(DeleteView):
    model = Artikel
    template_name = 'artikel/article_delete_notif.html'
    success_url = reverse_lazy('artikel:manage')

class ArticleManageView(ListView):
    model = Artikel
    template_name = 'artikel/article_manage.html'
    context_object_name = 'article'
    ordering = ['-published']

# class ArticleCreateView(CreateView):
#     form_class = ArtikelForm
#     template_name = 'article/article_create.html'

#     def get_context_data(self):
#         context = {
#             'page_title':'Create Article',
#             'button':'Tambah',
#             'form':self.form_class
#         }
#         return context

# class ArtikelPerKategori():
#     model = Article
#     context_object_name = 'latest_list'
#     # def get_latest_artikel(self):
#     #     kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
#     #     queryset = []
#     #     for kategori in kategori_list:
#     #         artikel = self.model.objects.values_list(kategori=kategori).latest('published')
#     #         queryset.append(artikel)
#     #     return queryset

class ArticleKategoriListView(ListView):
    model = Artikel
    template_name = 'artikel/article_category_list.html'
    context_object_name = 'article_list'
    ordering = ['-published']
    paginate_by = 3

    def get_queryset(self):
        self.queryset = self.model.objects.filter(kategori=self.kwargs['kategori'])
        print(self.queryset)
        return super().get_queryset()

    def get_context_data(self,*args,**kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)

class ArticleListView(ListView):
    model = Artikel
    template_name = 'artikel/article_list.html'
    context_object_name = 'article_list'
    ordering = ['-published']
    paginate_by = 3
    
    def get_context_data(self,*args,**kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)

class ArticleDetailView(DetailView):
    model = Artikel
    template_name = 'artikel/article_detail.html'
    context_object_name = 'article'

    def get_context_data(self,*args,**kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})

        artikel_serupa = self.model.objects.filter(kategori=self.object.kategori).exclude(id=self.object.id)
        self.kwargs.update({'artikel_serupa':artikel_serupa})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,TemplateView
from artikel.models import Artikel
# from artikel.views import ArtikelPerKategori

# class HomeBlogView(TemplateView,ArtikelPerKategori):
#     template_name = 'index.html'

#     def get_context_data(self):
#         querysets = self.get_latest_artikel()
#         context = {
#             'latest_list':querysets
#         }
#         return context

class HomeListView(ListView):
    model = Artikel
    rang = range(0, 1)
    template_name = 'index.html'
    context_object_name = 'latest_list'
    extra_context = {
        'range':rang,
    }
    ordering = ['-published']
    paginate_by = 6
    
    def get_context_data(self,*args,**kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list':kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args,**kwargs)

artikel/templates/artikel/article_category_list.html
{% extends "base.html" %}


{% block page_title %}
Artikel
{% endblock page_title %}


{% block contents %}



<div class="row">
    <div class="col-md-8">


        <h1 class="border-bottom">Artikel kategori {{kategori}}</h1>
        <br>
        {% for artikel in article_list %}
        <h1><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h1>
        <p>{{artikel.published}}</p>
        <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a></p>
        {% endfor %}

        {% if is_paginated %}
        <nav aria-label="ArticlePage">
            <ul class="pagination">
                {% if page_obj.has_previous %}    
                    <li class="page-item">
                        <a class="page-link" href="{% url 'artikel:category' kategori page_obj.previous_page_number %}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                {% endif %}
                    
                {% for page in paginator.page_range %}
                    
                    {% if page is page_obj.number %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
                            </li>
                    {% else %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'artikel:category' kategori page %}">{{page}}</a>
                            </li>
                    {% endif %}
                        
                
                {% endfor %}
            


                
                {% if page_obj.has_next %}    
                    <li class="page-item">
                        <a class="page-link" href="{% url 'artikel:category' kategori page_obj.next_page_number %}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        {% endif %}
    </div>
    <div class="col-sm">
        <h3>Kategori</h3>
        <ul class="list-group list-group-flush">
            {% for kategori in kategori_list %}
            <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1%}">{{kategori}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock contents %}

artikel/templates/artikel/article_create.html
{% extends 'base.html' %}

{% block page_title %}
{{page_title}}
{% endblock page_title %}


{% block contents %}
<h1>{{page_title}}</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for form in form %}
    <div class="form-group">
        <label for="{{form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
  {% endfor %}
    <br>
        <button type="submit" class="btn btn-primary">{{button}}</button>
</form>
{% endblock contents %}

artikel/templates/artikel/article_delete_notif.html
{% extends 'base.html' %}

{% block page_title %}
Delete Article Confirmation
{% endblock page_title %}


{% block contents %}
    <h1>Delete Article Confirmation</h1>
    <p>Apakah anda ingin menghapus artikel ini ? </p>
    <h3>{{article.judul}}</h3>
    <h3>{{article.published|date}}</h3>
    <form method="post">
        {% csrf_token %}
  <button type="submit" href="{% url 'artikel:create' %}" class="btn btn-danger">YA</button>
  <a type="button" href="{% url 'artikel:manage' %}" class="btn btn-primary">Tidak</a>
    </form>
{% endblock contents %}

artikel/templates/artikel/article_detail.html
{% extends "base.html" %}


{% block page_title %}
    {{article.judul}}
{% endblock page_title %}


{% block contents %}
<div class="row">
    <div class="col-md-8">
        <h1>{{article.judul}}</h1>
        <p>{{article.kategori}}|{{article.published}}</p>
        <div class="container">
        
        {% for f in article.File.all %}
            <!-- <img class="img-fluid" src="{{f.image.url}}" alt="Responsive image"> -->
        {% endfor %}
        
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
        {% for f in article.File.all %}
        
                {% if forloop.counter == 1 %}
                    <div class="carousel-item active">
                {% else %}
                    <div class="carousel-item">
                {% endif %}
                    <img width='480' height='360' class="d-block w-100" src="{{f.image.url}}" alt="First slide">
              </div>
        {% endfor %}        
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        
        
        <h6 style="text-align: center;">{{article.judul}}</h6>
        <br>    
        <br>
        </div>
        <p style="text-align:justify;">{{article.isi|linebreaksbr}}</p>
        <h3>Penulis: {{article.author}}</h3>
        <br>
        <div class="fb-comments" data-href="http://djblogade.herokuapp.com/blog/detail/{{article.slug}}" data-numposts="10" data-width=""></div>
        <br>
        
    </div>
    <div class="col-sm">
        <h3>Kategori</h3>
        <ul class="list-group list-group-flush">
            {% for kategori in kategori_list %}
                <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1%}">{{kategori}}</a></li>
            {% endfor %}
        </ul>
        <h3>Artikel Serupa</h3>
        <ul class="list-group list-group-flush">
            {% for artikel in artikel_serupa %}

                
                {% if forloop.counter is not 3 %}
                    <li class="list-group-item">
                        <a href="{% url 'artikel:detail' artikel.slug%}">{{artikel.judul}}</a>
                        <p>{{artikel.published|date}}</p>
                    </li>
                
                {% endif %}
                    
                
            {% endfor %}
                <li class="list-group-item">
                    <a href="{% url 'artikel:category' article.kategori 1%}">Selengkapnya</a>
                </li>
        </ul>
    </div>
</div>
    
{% endblock contents %}

artikel/templates/artikel/article_list.html
{% extends "base.html" %}


{% block page_title %}
Artikel
{% endblock page_title %}


{% block contents %}



<div class="row">
    <div class="col-md-8">

        <h1>Artikel</h1>
        {% for artikel in article_list %}
        <h1><a class="text-dark" href="{% url 'artikel:detail' artikel.slug %}">{{artikel.judul}}</a></h1>
        <p>{{artikel.kategori}} | {{artikel.published}}</p>
        <p class="border-bottom">{{artikel.isi|truncatewords:50}} <a href="{% url 'artikel:detail' artikel.slug %}">Selengkapnya</a>
            <br>
            <span class="badge badge-danger fb-comments-count" data-href="http://djblogade.herokuapp.com/blog/detail/{{artikel.slug}}"></span>
            Comments</p>

        {% endfor %}
        {% if is_paginated %}
        <nav aria-label="ArticlePage">
            <ul class="pagination">
                {% if page_obj.has_previous %}    
                    <li class="page-item">
                        <a class="page-link" href="{% url 'artikel:list' page_obj.previous_page_number %}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                {% endif %}
                    
                {% for page in paginator.page_range %}
                    
                    {% if page is page_obj.number %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
                            </li>
                    {% else %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'artikel:list' page %}">{{page}}</a>
                            </li>
                    {% endif %}
                        
                
                {% endfor %}
            


                
                {% if page_obj.has_next %}    
                    <li class="page-item">
                        <a class="page-link" href="{% url 'artikel:list' page_obj.next_page_number %}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        {% endif %}
    </div>
    <div class="col-sm">
        <h3>Kategori</h3>
        <ul class="list-group list-group-flush">
            {% for kategori in kategori_list %}
                <li class="list-group-item"><a href="{% url 'artikel:category' kategori 1%}">{{kategori}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock contents %}

artikel/templates/artikel/article_manage.html
{% extends "base.html" %}


{% block page_title %}
Manage Article
{% endblock page_title %}


{% block contents %}
<h1>Manage Article</h1>
<table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Judul</th>
        <th scope="col">Kategori</th>
        <th scope="col">Author</th>
        <th scope="col">Published</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody> 
        {% for article in article %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'artikel:detail' article.slug %}">{{article.judul}}</a></td>
            <td>{{article.kategori}}</td>
            <td>{{article.published|date}}</td>
            <td>{{article.author}}</td>
            <td>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Action
                    </button>
                    <div class="dropdown-menu">
                    </div>
                  </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% endblock contents %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'vendor/image/logo.png' %}">
    <title>
        {% block page_title %}

        {% endblock page_title %}
    </title>
    {% include "snippets/styles.html" %}
</head>

<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/id_ID/sdk.js#xfbml=1&version=v7.0">
    </script>
    {% include "snippets/navbar.html" %}
    <div class="container bg-light shadow-lg" style="margin-top:100px;">
        <br>
        <div class="container">
            {% block contents %}
            {% endblock contents %}
        </div>
        <br>
    </div>
    <br>
    <br>
    {% include "snippets/scripts.html" %}

</body>
{% include 'snippets/footer.html' %}

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
  Home
{% endblock page_title %}


{% block contents %}
  <h1 style="text-align: center;">Home</h1>
  <!-- <p>{{article_list}}</p> -->
  <div class="album py-5 bg-light">
    <div class="container">

        <div class="row">

            {% for post in latest_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    
                    {% with post.File.all|first as first_object %}
                        <img class="card-img-top" src="{{first_object.image.url}}"
                            data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail"
                            alt="Card image cap" height="150">
                    {% endwith %}     
                    <div class="card-body">
                        <a href="{% url 'artikel:detail' post.slug %}"><b style="font-size:large">{{post.judul}}</b></a>
                        <p class="card-text">{{post.isi|truncatechars:200}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'artikel:detail' post.slug %}" type="button"
                                    class="btn btn-sm btn-outline-primary">Selengkapnya</a>
                            </div>
                            <small class="text-muted">{{post.published}}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
        <nav aria-label="ArticlePage">
            <ul class="pagination">
                {% if page_obj.has_previous %}    
                    <li class="page-item">
                        <a class="page-link" href="{% url 'home' page_obj.previous_page_number %}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                {% endif %}
                    
                {% for page in paginator.page_range %}
                    
                    {% if page is page_obj.number %}
                            <li class="page-item active" aria-current="page">
                                <span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
                            </li>
                    {% else %}
                            <li class="page-item">
                                <a class="page-link" href="{% url 'home' page %}">{{page}}</a>
                            </li>
                    {% endif %}
                        
                
                {% endfor %}
            


                
                {% if page_obj.has_next %}    
                    <li class="page-item">
                        <a class="page-link" href="{% url 'home' page_obj.next_page_number %}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        {% endif %}
    </div>
</div>
{% endblock contents %}

templates/snippets/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue bg-dark">

    <!-- Copyright -->
    <div class="text-light footer-copyright text-center py-3">
        Powerful Website Created with Django Python Framework
        <br>
        © 2020 Copyright:
      <a href="https://mdbootstrap.com/"> SN.net</a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

templates/snippets/navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' 1%}">
            <img width="40" height="40" src="{% static 'vendor/image/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' 1%}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'artikel:list' 1 %}">Article</a>
                </li>
                
            </ul>
            <div class="nav-item dropdown ml-auto">
                    <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        Admin
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Login</a>
                    </div>
                </div>
        </div>
    </div>
</nav>

templates/snippets/scripts.html
{% load static %}
<script src="{% static 'vendor/jquery/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<style>
    body {
        background:url("{% static 'vendor/image/bg.jpg' %}") no-repeat center center fixed; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
</style>